# Generated by Django 5.0.4 on 2024-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_reservaservicio_precio_original_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(default='Ushuaia', max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('comentarios', models.CharField(max_length=100)),
                ('grupo', models.CharField(choices=[('Mutual Luz y Fuerza', 'Mutual Luz y Fuerza')], max_length=30)),
            ],
        ),
    ]
