# Generated by Django 5.0.4 on 2024-05-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apeynombre', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=30)),
                ('repeat_contrasenia', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(default='netcell@gmail.com', max_length=30)),
                ('dni', models.IntegerField()),
                ('locales', models.CharField(choices=[('deposito', 'Deposito'), ('shopping', 'Shopping'), ('rosas', 'Rosas')], default='rosas', max_length=20)),
                ('roles', models.CharField(choices=[('tecnico', 'Servicio Tecnico'), ('ventas', 'Usuario ventas'), ('admin', 'Administrador')], default='usuario', max_length=7)),
            ],
        ),
    ]
