# Generated by Django 5.0.4 on 2024-05-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('ganancia', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stockMinimo', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Mutual Luz y Fuerza', 'Mutual Luz y Fuerza')], max_length=30)),
                ('proveedor', models.CharField(choices=[('Mutual Luz y Fuerza', 'Mutual Luz y Fuerza')], max_length=30)),
                ('ubicacion', models.CharField(choices=[('Depósito', 'Depósito'), ('Shopping', 'Shopping'), ('Rosas', 'Rosas')], max_length=30)),
            ],
        ),
    ]
