# Generated by Django 5.0.4 on 2024-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apeynombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='repeat_contrasenia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.CharField(choices=[('tecnico', 'Servicio Tecnico'), ('ventas', 'Usuario ventas'), ('admin', 'Administrador')], max_length=7),
        ),
    ]
