# Generated by Django 5.0.4 on 2024-05-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0027_remove_usuario_apeynombre_remove_usuario_contrasenia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
